### ISSUE TITLE
issue with lsf-drmaa

### ISSUE THREAD

**Issue by ink1** [pygridtools/drmaa-python#14]
Hello,
Could you think of a reason why drmaa-python and lsf-drmaa
https://github.com/PlatformLSF/lsf-drmaa
would segfault on RH 6.4 but not on opensuse 12.1?
Trying some of the examples, I can see a job gets submitted (and run) but Python segfaults.
Thanks

**Comment by jakirkham** [comment]
Have been using a recent copy of lsf-drmaa and drmaa-python without issues. So maybe this was fixed at some point in one of them?

**Comment by zihhuafang** [comment]
I am having issue with lsf-drmaa(1.1.1) and drmaa-python (0.7.9) with string formatting.
I ran the following test script to see what might causes the issue

#!/usr/bin/env python

import drmaa

def main():
    """ Query the system. """
    with drmaa.Session() as s:
        print('A DRMAA object was created')
        print('Supported contact strings: %s' % s.contact)
        print('Supported DRM systems: %s' % s.drmsInfo)
        print('Supported DRMAA implementations: %s' % s.drmaaImplementation)
        print('Version %s' % s.version)

        print('Exiting')

if __name__=='__main__':
    main()

I got the following error message:

A DRMAA object was created
Supported contact strings:
Supported DRM systems: IBM Spectrum LSF 10.1
Supported DRMAA implementations: FedStage DRMAA for LSF 1.1.1
Traceback (most recent call last):
  File "./test.py", line 17, in <module>
    main()
  File "./test.py", line 12, in main
    print('Version %s' % s.version)
TypeError: not all arguments converted during string formatting

Anyone has an idea how to fix it?
