### ISSUE TITLE
Update scripts in examples directory to match current tutorial code

### ISSUE THREAD

**Issue by dan-blanchard** [pygridtools/drmaa-python#32]
Currently, the scripts in the examples directory haven't been touched for many years.  The [RTD tutorial](http://drmaa-python.readthedocs.org/en/latest/tutorials.html) is much more up-to-date.

**Comment by stevekm** [comment]
What is the status of these example scripts? Are they supposed to work? I cannot get them to work, not sure if its due to the issue mentioned here or not;

```
$ python drmaa-python/examples/example1.py

Unable to communicate with master.cm.cluster(192.168.10.1)
A session was started successfully
Traceback (most recent call last):
  File "drmaa-python/examples/example1.py", line 15, in <module>
    main()
  File "drmaa-python/examples/example1.py", line 12, in main
    s.exit()
  File "/ifs/data/molecpathlab/venv/lib/python2.7/site-packages/drmaa/session.py", line 271, in exit
    py_drmaa_exit()
  File "/ifs/data/molecpathlab/venv/lib/python2.7/site-packages/drmaa/wrappers.py", line 80, in py_drmaa_exit
    return _lib.drmaa_exit(error_buffer, sizeof(error_buffer))
  File "/ifs/data/molecpathlab/venv/lib/python2.7/site-packages/drmaa/errors.py", line 151, in error_check
    raise _ERRORS[code - 1](error_string)
drmaa.errors.NoActiveSessionException: code 5: drmaa: No active DRMAA session.

```

I also have these set, not sure if its related:

```
$ echo $SGE_ROOT
/cm/shared/apps/sge/2011.11p1
$ echo $SGE_CELL
default
```
